### ISSUE TITLE
我想问下你是怎么读的网站呀？

### ISSUE THREAD

**Issue by kingvern** [jelly54/crawler#1]
我想问下你是怎么读的网站呀？我试过各种浏览器根本看不了

**Comment by jelly54** [comment]
> 我想问下你是怎么读的网站呀？我试过各种浏览器根本看不了

哪个脚本呢？有的是通过网站，有的是通过app。但是逻辑都是一样的。

1. 观察页面跳转逻辑
2. 找访问接口
3. 用抓包工具统计
4. 得到request
5. 使用编程语言伪造request请求
6. 对获得的response结果进行处理
