### ISSUE TITLE
mm131抓取未考虑ID在4位数的情况

### ISSUE THREAD

**Issue by coralfox** [jelly54/crawler#5]
源代码,直接取的4位,如果出现3位,2位,就会出现字符 
`latest_id = hrefs[index][-9:-5]`   

用/分割,取倒数第一个即可
`latest_id = hrefs[index][-9:-5].split("/")[-1]`

懒得推送了..直接写出来了

**Comment by jelly54** [comment]
> 源代码,直接取的4位,如果出现3位,2位,就会出现字符 `latest_id = hrefs[index][-9:-5]`
> 
> 用/分割,取倒数第一个即可 `latest_id = hrefs[index][-9:-5].split("/")[-1]`
> 
> 懒得推送了..直接写出来了

这个解析策略也是可以的:+1:，但是现在网站挂了:scream: ，后续不再维护了。感谢您的issue
